### ISSUE TITLE
建议在 read.me 中介绍回调函数中的参数

### ISSUE THREAD

**Issue by Hanruis** [darkgeek/Phonegap-BaiduGeolocation-Plugin#1]
感谢提供插件。希望能够在 read.me 中加入对回调函数的参数说明。虽然说使用方式和 w3c 的接口标准一样，但不禁还是疑惑。

**Comment by darkgeek** [comment]
@Hanruis 您好，我在README.md中，对`getCurrentPosition`的使用方法做了更多的介绍，希望能解决您的疑惑。

**Comment by Hanruis** [comment]
感谢。:)
