### ISSUE TITLE
cordova build 不会将 plugin.xml 的配置写入 AndroidManifest.xml 里面，导致 key 为空

### ISSUE THREAD

**Issue by Hanruis** [darkgeek/Phonegap-BaiduGeolocation-Plugin#2]
我是通过在 plugins 目录下的 android.json 文件，直接修改里面的 key 解决这个问题的。似乎 cordova build 的时候，不会再读取 plugin.xml 文件，而是直接读取 plugins 下的 android.json 文件。提出个问题，希望能够对后面使用这个插件的人有帮助。

**Comment by darkgeek** [comment]
@Hanruis 谢谢，可能是因为我在开发此插件时就填上了我自己的key，用的时候也不需要去修改key，所以一直没有注意到这个问题。现在已经在`README.md`里写了相关的内容。
